### PR TITLE
abort register if username already exists

### PR DESCRIPTION
**Pull request by epsilontheta**
See https://github.com/Lommix/WichtelBotTheSequel/issues/1

### CODE REVIEW

**Comment by epsilontheta** [comment]
See #1

**Comment by Lommix** [comment]
nice!

**Comment by epsilontheta** [comment]
Great :) I have some ideas for improving the user login btw. Mostly its about generating a login link for a specific party and making it more visible. I might send you a PR soon :D. Would like to hear your opinion about that. Glad I found your project. Its so much better than what we did before.

**Comment by Lommix** [comment]
I will happily accept any improvement. One thing that annoys me the most is that the 3-day auto delete can not be configured in the .env. Last year I had to restart, because grandma was too slow/lazy to deal with technologies xD
Also, the donate button should be removed, dead link anyway.

I will support you with any change!

**Pull request merged**
